### ISSUE TITLE
A typo in the "little" word when detecting the endianess

### ISSUE THREAD

**Issue by galaxy4public** [PeterPawn/modfs#18]
There is a typo in https://github.com/PeterPawn/modfs/blob/master/modfs#L743 where "little" was spelt as "litte" (missing "l") so the endianess detection does not work as expected.

**Comment by PeterPawn** [comment]
Thx, will be corrected soon.

But afaik there's no NAND based device available from AVM (yet), which uses LE encoding ... that's why there's no hurry (for general users). Only an adaption to other platforms would be affected at the time of this writing.

**Comment by PeterPawn** [comment]
corrected with 4d7992eb90c6e3a1b7bafceaa19738ef26df6075
