### ISSUE TITLE
Does this work with 6.52

### ISSUE THREAD

**Issue by 3djake** [PeterPawn/modfs#23]
Hi is there a way to get this to working with firmware version 6.52?

It appears they are checking for signatures, I would really like to get telnet access to a fritzbox 7490.

**Comment by muhviehstah** [comment]
while no answer 
do
try and error

echo $result > $thiscommentfield

:)))


telnet access on 7490 6.52+ works good

**Comment by PeterPawn** [comment]
I had no subscription for issues here ... at least until now - so I didn't realize, that there was a new entry.

Any downloaded image will be checked with the public keys present in the *running* system.

If you try to install different (localized) systems, you may specify "NOVERIFY=1" as environment variable while calling "modfs" to suppress the whole integrity check of downloaded images.
