### ISSUE TITLE
telnetd on 7390 @ 6.83

### ISSUE THREAD

**Issue by lugg8** [PeterPawn/modfs#28]
Hey Peter,
I am looking around since weeks to find the right way to reach my goal. I am not sure what the right way is to have a telnetd acess to my 7390 FB from AVM. 
I was looking through the IP forum which gave me not a clear picture of what the right way is to go.
my assumption by now is:
1. place any file (modfs, ..) to the usb drive of my FB
2. place the FW 6.83 to the usb drive
3. modify this firmware 
4. sign this firmware
5. upload this firmware to the device.

(by the way: i would have this RuKernelTool) if this would help me in reaching my goal.

it would be great if you might show me the right way to go here.

many thanks in advance. 

Best
Alex

**Comment by PeterPawn** [comment]
Please use the Freetz project to handle a 7390 model ... "modfs" was only designed to be usable for models based on NAND-flash for the operating system and the 7390 model uses the old(er) NOR-based mechanisms.

Please look for: 
http://trac.freetz.org/changeset/13796
http://trac.freetz.org/wiki/help/howtos/development/repack_fw#Verwendungvonfwmodimnofreetz-Modus
http://freetz.org/wiki/help/howtos/development/repack_fw

**Comment by lugg8** [comment]
many thanks! I was aware of the freetz project, but i thought the last development was stopped since 2012. this does not apply for SW Versions up to 6.83 from 2017! 
what exacly do I need to do? 
Does this RuKernelTool help me with anything?

**Comment by PeterPawn** [comment]
No, the ruKernelTool may not help you here ... it may only be used to install a modified firmware, but as far as I understand it, your problem is to get such a modified firmware image first.

Please try to read the hints from Freetz (mentioned above) first and ask concrete questions (usually it's even better to **ask further questions in the "IPPF arena"**, too), if you can't understand something.

The Freetz project is still alive and usable for 84.06.83 (with the full power of Freetz modifications or only as a tool to modify the original firmware slightly) and many later firmware versions for other models. 

Have a look at the "trunk" (it's the developer version, but no other branches are supported anymore for new versions) ... you may find this branch on GitHub as "master" for the Freetz project, too.

**Comment by lugg8** [comment]
got everything what you mentioned.
I have downloaded each code (fwmod, fwmod_custom, freetzfunctions) and added them to my fritzbox over USB stick to /var/temp as well as the current SW 6.83.
my problem is that Í am not able to execute this files (codes)
what the hell are I am doing wrong? it should be very easy, isn't it?

or is there any image which I only need to flash (6.83 with added telnetd client)

**Comment by lugg8** [comment]
![fb](https://user-images.githubusercontent.com/32571230/31287545-e82f0c0e-aac1-11e7-8e0a-a69dbb66b215.GIF)
![fb_](https://user-images.githubusercontent.com/32571230/31287551-ebec9000-aac1-11e7-8fb9-17504be9255c.GIF)

**Comment by PeterPawn** [comment]
You have to **read** the linked sources and not to download any of the mentioned files without an idea, what you should do with it.

You need to clone the Freetz toolchain to any Linux system (take the prerequisites into account) and execute all actions to modify the firmware on this Linux system ... the outcome is an own firmware image, which may be installed on the box in question. This installation can be done in an "easy way" or you may use your favorite "ruKernelTool" for this task.

And once again ... here is the wrong place to discuss any modifications related to a 7390 device. First reason at all - the "modfs" project is not intended to be used with NOR-based boxes (look at its title). And there are better places to ask question regarding the Freetz project ... the best one is the IPPF forum at https://www.ip-phone-forum.de/forums/freetz.525 - please use this for further questions.

**Comment by lugg8** [comment]
hey peter,
many thanks for your help. finally got there :-)
may you give me the hint, which package/tool I need to activate to get telnetd like it was usual. 
I have tried different and I am not sure which one is the right to activate.
Best
Thanks once again
